// Central catalog for the navbar search — kept in sync with Leaderboard and Game.tsx.
export const ALL_GAMES = [
  { id: 'block-blast', title: 'Block Blast', category: 'Puzzle', rating: 4.8, color: 'hsl(185, 100%, 50%)' },
  { id: 'block-blast-extreme', title: 'Block Blast Extreme', category: 'Puzzle', rating: 4.7, color: 'hsl(280, 100%, 60%)' },
  { id: 'tetris', title: 'Tetris', category: 'Puzzle', rating: 4.9, color: 'hsl(280, 100%, 60%)' },
  { id: 'pac-man', title: 'Pac-Man', category: 'Arcade', rating: 4.9, color: 'hsl(45, 100%, 55%)' },
  { id: 'snake', title: 'Snake', category: 'Arcade', rating: 4.7, color: 'hsl(142, 76%, 50%)' },
  { id: 'wordle', title: 'Wordle', category: 'Word', rating: 4.9, color: 'hsl(142, 76%, 40%)' },
  { id: 'chess', title: 'Chess', category: 'Strategy', rating: 4.9, color: 'hsl(30, 20%, 30%)' },
  { id: 'checkers', title: 'Checkers', category: 'Strategy', rating: 4.7, color: 'hsl(30, 20%, 30%)' },
  { id: 'geometry-dash', title: 'Geometry Dash', category: 'Action', rating: 4.9, color: 'hsl(320, 100%, 60%)' },
  { id: '2048', title: '2048', category: 'Puzzle', rating: 4.8, color: 'hsl(30, 100%, 50%)' },
  { id: 'flappy', title: 'Flappy Bird', category: 'Arcade', rating: 4.6, color: 'hsl(45, 100%, 55%)' },
  { id: 'sudoku', title: 'Sudoku', category: 'Puzzle', rating: 4.7, color: 'hsl(210, 100%, 45%)' },
  { id: 'memory', title: 'Memory Match', category: 'Puzzle', rating: 4.6, color: 'hsl(320, 100%, 60%)' },
  { id: 'clicker', title: 'Click Frenzy', category: 'Idle', rating: 4.5, color: 'hsl(45, 100%, 55%)' },
  { id: 'racing', title: 'Neon Racer', category: 'Racing', rating: 4.7, color: 'hsl(320, 100%, 60%)' },
  { id: 'maze', title: 'Maze Runner', category: 'Puzzle', rating: 4.5, color: 'hsl(220, 80%, 55%)' },
  { id: 'pong', title: 'Pong', category: 'Classic', rating: 4.6, color: 'hsl(0, 0%, 90%)' },
  { id: 'brick-breaker', title: 'Brick Breaker', category: 'Arcade', rating: 4.6, color: 'hsl(20, 90%, 55%)' },
  { id: 'space-invaders', title: 'Space Invaders', category: 'Shooter', rating: 4.8, color: 'hsl(140, 80%, 50%)' },
  { id: 'asteroids', title: 'Asteroids', category: 'Shooter', rating: 4.7, color: 'hsl(0, 0%, 80%)' },
  { id: 'dino-run', title: 'Dino Run', category: 'Runner', rating: 4.7, color: 'hsl(90, 40%, 50%)' },
  { id: 'hangman', title: 'Hangman', category: 'Word', rating: 4.5, color: 'hsl(30, 30%, 45%)' },
  { id: 'tic-tac-toe', title: 'Tic Tac Toe', category: 'Strategy', rating: 4.4, color: 'hsl(0, 0%, 70%)' },
  { id: 'connect-four', title: 'Connect Four', category: 'Strategy', rating: 4.6, color: 'hsl(45, 100%, 55%)' },
  { id: 'minesweeper', title: 'Minesweeper', category: 'Puzzle', rating: 4.7, color: 'hsl(220, 30%, 50%)' },
  { id: 'simon-says', title: 'Simon Says', category: 'Memory', rating: 4.6, color: 'hsl(140, 70%, 50%)' },
  { id: 'whack-a-mole', title: 'Whack-a-Mole', category: 'Arcade', rating: 4.5, color: 'hsl(30, 60%, 45%)' },
  { id: 'fruit-slice', title: 'Fruit Slice', category: 'Arcade', rating: 4.7, color: 'hsl(0, 90%, 55%)' },
  { id: 'crossy-road', title: 'Crossy Road', category: 'Arcade', rating: 4.7, color: 'hsl(140, 60%, 50%)' },
  { id: 'temple-run', title: 'Temple Run', category: 'Runner', rating: 4.6, color: 'hsl(30, 60%, 40%)' },
  { id: 'dodge-ball', title: 'Dodge Ball', category: 'Arcade', rating: 4.5, color: 'hsl(0, 80%, 55%)' },
  { id: 'color-match', title: 'Color Match', category: 'Brain', rating: 4.6, color: 'hsl(280, 80%, 60%)' },
  { id: 'word-search', title: 'Word Search', category: 'Word', rating: 4.6, color: 'hsl(200, 70%, 50%)' },
  { id: 'quiz', title: 'Quiz Challenge', category: 'Trivia', rating: 4.7, color: 'hsl(260, 70%, 55%)' },
  { id: 'breakout', title: 'Breakout', category: 'Arcade', rating: 4.6, color: 'hsl(20, 90%, 55%)' },
  { id: 'solitaire', title: 'Solitaire', category: 'Card', rating: 4.7, color: 'hsl(140, 60%, 45%)' },
  { id: 'bubble-shooter', title: 'Bubble Shooter', category: 'Puzzle', rating: 4.6, color: 'hsl(200, 90%, 60%)' },
  { id: 'jigsaw', title: 'Jigsaw Puzzle', category: 'Puzzle', rating: 4.5, color: 'hsl(30, 60%, 50%)' },
  { id: 'spin-wheel', title: 'Spin Wheel', category: 'Luck', rating: 4.4, color: 'hsl(320, 90%, 55%)' },
  { id: 'type-racer', title: 'Type Racer', category: 'Skill', rating: 4.6, color: 'hsl(200, 70%, 55%)' },
  { id: 'reaction', title: 'Reaction Test', category: 'Skill', rating: 4.5, color: 'hsl(45, 100%, 55%)' },
  { id: 'number-guess', title: 'Number Guess', category: 'Puzzle', rating: 4.4, color: 'hsl(210, 60%, 55%)' },
  { id: 'rps', title: 'Rock Paper Scissors', category: 'Classic', rating: 4.5, color: 'hsl(30, 60%, 50%)' },
  { id: 'catch', title: 'Catch Game', category: 'Arcade', rating: 4.4, color: 'hsl(45, 100%, 55%)' },
  { id: 'platform-jump', title: 'Platform Jump', category: 'Arcade', rating: 4.5, color: 'hsl(140, 70%, 50%)' },
  { id: 'tower-stack', title: 'Tower Stack', category: 'Skill', rating: 4.6, color: 'hsl(200, 90%, 55%)' },
  { id: 'color-switch', title: 'Color Switch', category: 'Arcade', rating: 4.5, color: 'hsl(280, 80%, 60%)' },
  { id: 'pattern-memory', title: 'Pattern Memory', category: 'Memory', rating: 4.6, color: 'hsl(200, 70%, 50%)' },
  { id: 'spot-difference', title: 'Spot Difference', category: 'Puzzle', rating: 4.5, color: 'hsl(30, 70%, 55%)' },
  { id: 'math-blitz', title: 'Math Blitz', category: 'Brain', rating: 4.6, color: 'hsl(260, 70%, 55%)' },
  { id: 'balloon-pop', title: 'Balloon Pop', category: 'Arcade', rating: 4.5, color: 'hsl(320, 90%, 60%)' },
  { id: 'pipe-connect', title: 'Pipe Connect', category: 'Puzzle', rating: 4.6, color: 'hsl(200, 70%, 50%)' },
  { id: 'lights-out', title: 'Lights Out', category: 'Puzzle', rating: 4.5, color: 'hsl(45, 100%, 55%)' },
  { id: 'word-scramble', title: 'Word Scramble', category: 'Word', rating: 4.5, color: 'hsl(200, 70%, 50%)' },
  { id: 'coin-dash', title: 'Coin Dash', category: 'Arcade', rating: 4.6, color: 'hsl(45, 100%, 55%)' },
  { id: 'skeet-shoot', title: 'Skeet Shoot', category: 'Skill', rating: 4.5, color: 'hsl(200, 70%, 50%)' },
  { id: 'hex-merge', title: 'Hex Merge', category: 'Puzzle', rating: 4.6, color: 'hsl(280, 80%, 60%)' },
  { id: 'gravity-runner', title: 'Gravity Runner', category: 'Runner', rating: 4.7, color: 'hsl(280, 80%, 60%)' },
  { id: 'ice-slider', title: 'Ice Slider', category: 'Puzzle', rating: 4.5, color: 'hsl(195, 80%, 60%)' },
  { id: 'roblox-obby', title: 'Roblox Obby', category: '3D', rating: 4.9, color: 'hsl(140, 80%, 50%)' },
  { id: 'stack-tower-3d', title: 'Stack Tower', category: 'Skill', rating: 4.8, color: 'hsl(185, 100%, 50%)' },
  { id: 'helix-jump', title: 'Helix Jump', category: 'Arcade', rating: 4.9, color: 'hsl(45, 100%, 55%)' },
  { id: 'cube-runner', title: 'Cube Runner', category: 'Runner', rating: 4.8, color: 'hsl(280, 100%, 60%)' },
  { id: 'doodle-jump', title: 'Doodle Jump', category: 'Arcade', rating: 4.7, color: 'hsl(142, 76%, 50%)' },
  { id: 'ball-sort', title: 'Ball Sort', category: 'Puzzle', rating: 4.8, color: 'hsl(185, 100%, 50%)' },
  { id: 'match-3', title: 'Match-3 Mania', category: 'Puzzle', rating: 4.7, color: 'hsl(320, 100%, 60%)' },
  { id: 'nonogram', title: 'Nonogram', category: 'Puzzle', rating: 4.6, color: 'hsl(280, 100%, 60%)' },
  { id: 'word-connect', title: 'Word Connect', category: 'Word', rating: 4.7, color: 'hsl(45, 100%, 55%)' },
  { id: 'slime-volley', title: 'Slime Volley', category: 'Sports', rating: 4.8, color: 'hsl(200, 100%, 50%)' },
  { id: 'tower-defense', title: 'Tower Defense', category: 'Strategy', rating: 4.9, color: 'hsl(220, 100%, 55%)' },
  { id: 'find-match', title: 'Find Match', category: 'Multiplayer', rating: 4.9, color: 'hsl(320, 100%, 60%)' },
  { id: 'guess-the-person', title: 'Guess The Person', category: 'Plus', rating: 5.0, color: 'hsl(45, 100%, 55%)' },
  { id: 'crash-it', title: 'Crash It', category: 'Multiplayer', rating: 4.9, color: 'hsl(0, 100%, 60%)' },
  { id: 'tanks', title: 'Tanks', category: 'Plus', rating: 4.9, color: 'hsl(210, 90%, 55%)' },
  { id: 'aim-trainer', title: 'Aim Trainer', category: 'Skill', rating: 4.7, color: 'hsl(0, 90%, 55%)' },
  { id: 'piano-tiles', title: 'Piano Tiles', category: 'Skill', rating: 4.8, color: 'hsl(240, 15%, 25%)' },
  { id: 'sliding-puzzle', title: 'Sliding Puzzle', category: 'Puzzle', rating: 4.6, color: 'hsl(200, 80%, 55%)' },
  { id: 'emoji-match', title: 'Emoji Match', category: 'Brain', rating: 4.7, color: 'hsl(45, 100%, 60%)' },
  { id: 'falling-dodge', title: 'Falling Dodge', category: 'Arcade', rating: 4.8, color: 'hsl(0, 100%, 60%)' },
  { id: 'color-rush', title: 'Color Rush', category: 'Brain', rating: 4.7, color: 'hsl(320, 100%, 60%)' },
  { id: 'higher-lower', title: 'Higher or Lower', category: 'Casual', rating: 4.6, color: 'hsl(140, 70%, 50%)' },
  { id: 'coin-miner', title: 'Coin Miner', category: 'Puzzle', rating: 4.7, color: 'hsl(50, 95%, 55%)' },
  { id: 'meteor-shower', title: 'Meteor Shower', category: 'Shooter', rating: 4.8, color: 'hsl(20, 100%, 55%)' },
  { id: 'ultra-blitz', title: 'Ultra Blitz', category: 'Plus', rating: 5.0, color: 'hsl(280, 100%, 60%)' },
  { id: 'sand-cutting', title: 'Sand Cutting', category: 'ASMR', rating: 4.8, color: 'hsl(28, 70%, 60%)' },
  { id: 'bubble-wrap', title: 'Bubble Wrap', category: 'ASMR', rating: 4.8, color: 'hsl(190, 85%, 60%)' },
  { id: 'slime-squish', title: 'Slime Squish', category: 'ASMR', rating: 4.8, color: 'hsl(150, 80%, 55%)' },
  { id: 'zen-garden', title: 'Zen Garden', category: 'ASMR', rating: 4.8, color: 'hsl(40, 40%, 70%)' },
  { id: 'water-ripples', title: 'Water Ripples', category: 'ASMR', rating: 4.8, color: 'hsl(195, 90%, 60%)' },
  { id: 'pressure-wash', title: 'Pressure Wash', category: 'ASMR', rating: 4.8, color: 'hsl(205, 70%, 55%)' },
  { id: 'soap-carving', title: 'Soap Carving', category: 'Plus', rating: 4.8, color: 'hsl(320, 70%, 65%)' },
  { id: 'tower-demolition', title: 'Tower Demolition', category: 'Destruction', rating: 4.8, color: 'hsl(20, 90%, 55%)' },
  { id: 'glass-smash', title: 'Glass Smash', category: 'Destruction', rating: 4.8, color: 'hsl(180, 90%, 60%)' },
  { id: 'reversi', title: 'Reversi', category: 'Strategy', rating: 4.7, color: 'hsl(142, 70%, 45%)' },
  { id: 'cup-shuffle', title: 'Cup Shuffle', category: 'Skill', rating: 4.6, color: 'hsl(45, 100%, 55%)' },
  { id: 'bomb-defuse', title: 'Bomb Defuse', category: 'Brain', rating: 4.8, color: 'hsl(0, 85%, 55%)' },
];
